package CenterServerModule;

/**
* CenterServerModule/ICenterServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ICenterServer.idl
* Saturday, July 28, 2018 9:36:28 o'clock AM EDT
*/

public final class ICenterServerHolder implements org.omg.CORBA.portable.Streamable
{
  public CenterServerModule.ICenterServer value = null;

  public ICenterServerHolder ()
  {
  }

  public ICenterServerHolder (CenterServerModule.ICenterServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CenterServerModule.ICenterServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CenterServerModule.ICenterServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CenterServerModule.ICenterServerHelper.type ();
  }

}
