package CenterServerModule;


/**
* CenterServerModule/ICenterServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ICenterServer.idl
* Saturday, July 28, 2018 9:36:28 o'clock AM EDT
*/

public interface ICenterServer extends ICenterServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ICenterServer
