package CenterServerModule;


/**
* CenterServerModule/ICenterServerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ICenterServer.idl
* Saturday, July 28, 2018 9:36:28 o'clock AM EDT
*/

public abstract class ICenterServerPOA extends org.omg.PortableServer.Servant
 implements CenterServerModule.ICenterServerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createTRecord", new java.lang.Integer (0));
    _methods.put ("createSRecord", new java.lang.Integer (1));
    _methods.put ("getRecordCounts", new java.lang.Integer (2));
    _methods.put ("editRecord", new java.lang.Integer (3));
    _methods.put ("editListRecord", new java.lang.Integer (4));
    _methods.put ("transferRecord", new java.lang.Integer (5));
    _methods.put ("printHashMap", new java.lang.Integer (6));
    _methods.put ("killThreads", new java.lang.Integer (7));
    _methods.put ("shutdown", new java.lang.Integer (8));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CenterServerModule/ICenterServer/createTRecord
       {
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String address = in.read_string ();
         String phone = in.read_string ();
         String specialization = in.read_string ();
         String location = in.read_string ();
         String managerId = in.read_string ();
         boolean $result = false;
         $result = this.createTRecord (firstName, lastName, address, phone, specialization, location, managerId);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // CenterServerModule/ICenterServer/createSRecord
       {
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String courseRegistered = in.read_string ();
         String status = in.read_string ();
         String statusDate = in.read_string ();
         String managerId = in.read_string ();
         boolean $result = false;
         $result = this.createSRecord (firstName, lastName, courseRegistered, status, statusDate, managerId);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // CenterServerModule/ICenterServer/getRecordCounts
       {
         String managerId = in.read_string ();
         String $result = null;
         $result = this.getRecordCounts (managerId);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // CenterServerModule/ICenterServer/editRecord
       {
         String recordId = in.read_string ();
         String fieldName = in.read_string ();
         String newValue = in.read_string ();
         String managerId = in.read_string ();
         String $result = null;
         $result = this.editRecord (recordId, fieldName, newValue, managerId);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // CenterServerModule/ICenterServer/editListRecord
       {
         String recordId = in.read_string ();
         String fieldName = in.read_string ();
         String newValue = in.read_string ();
         String managerId = in.read_string ();
         String $result = null;
         $result = this.editListRecord (recordId, fieldName, newValue, managerId);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // CenterServerModule/ICenterServer/transferRecord
       {
         String managerId = in.read_string ();
         String recordId = in.read_string ();
         String targetCenterName = in.read_string ();
         boolean $result = false;
         $result = this.transferRecord (managerId, recordId, targetCenterName);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 6:  // CenterServerModule/ICenterServer/printHashMap
       {
         this.printHashMap ();
         out = $rh.createReply();
         break;
       }

       case 7:  // CenterServerModule/ICenterServer/killThreads
       {
         this.killThreads ();
         out = $rh.createReply();
         break;
       }

       case 8:  // CenterServerModule/ICenterServer/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CenterServerModule/ICenterServer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ICenterServer _this() 
  {
    return ICenterServerHelper.narrow(
    super._this_object());
  }

  public ICenterServer _this(org.omg.CORBA.ORB orb) 
  {
    return ICenterServerHelper.narrow(
    super._this_object(orb));
  }


} // class ICenterServerPOA
